sudo: required
services: 
  - docker

before_install:
  - docker build -t smaraswa/react-test -f ./client/Dockerfile.dev ./

script:
  - docker run smaraswa/react-test npm test -- -- coverage

after-success:
  - docker build -t smaraswa/multi-client ./client
  - docker build -t smaraswa/multi-nginx ./nginx
  - docker build -t smaraswa/multi-worker ./worker
  - docker build -t smaraswa/multi-server ./server



